<?php

require __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$host = $_ENV['DB_HOST'];
$db   = $_ENV['DB_DATABASE'];
$user = $_ENV['DB_USERNAME'];
$pass = $_ENV['DB_PASSWORD'];

try {
    $pdo = new PDO('pgsql:host=' . $host . ';port=' . ($_ENV['DB_PORT'] ?? '5432') . ';dbname=' . $db, $user, $pass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    echo "Checking watchlists table...\n";
    echo str_repeat("=", 80) . "\n\n";
    
    // Check if watchlists table exists
    $result = $pdo->query("SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename = 'watchlists'");
    
    if ($result->rowCount() > 0) {
        echo "✓ watchlists table exists\n\n";
        
        // Show structure
        echo "Table structure:\n";
        $columns = $pdo->query("SELECT column_name AS Field, data_type AS Type FROM information_schema.columns WHERE table_name = 'watchlists' ORDER BY ordinal_position");
        foreach ($columns as $column) {
            echo "  - {$column['field']} ({$column['type']})\n";
        }
        
        // Count records
        $count = $pdo->query("SELECT COUNT(*) as total FROM watchlists")->fetch();
        echo "\nTotal records: {$count['total']}\n";
        
    } else {
        echo "✗ watchlists table does NOT exist\n\n";
        echo "Creating watchlists table...\n";
        
        $pdo->exec("
            CREATE TABLE watchlists (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                film_id INTEGER NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_watchlists_user_film UNIQUE (user_id, film_id),
                CONSTRAINT fk_watchlists_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                CONSTRAINT fk_watchlists_film FOREIGN KEY (film_id) REFERENCES movies(id) ON DELETE CASCADE
            )
        ");
        
        echo "✓ watchlists table created successfully\n";
    }
    
} catch (PDOException $e) {
    echo "Error: " . $e->getMessage() . "\n";
}
