<?php

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use Illuminate\Support\Facades\DB;

echo "========================================\n";
echo "CHECKING MOVIE_LIKES TABLE\n";
echo "========================================\n\n";

// Check if table exists
$tables = DB::select("SELECT tablename AS name FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename");

$tableExists = false;
foreach ($tables as $table) {
    if ($table->name === 'movie_likes') {
        $tableExists = true;
        break;
    }
}

if ($tableExists) {
    echo "✅ Table 'movie_likes' exists\n\n";
    
    // Show structure
    echo "Table Structure:\n";
    $columns = DB::select("SELECT column_name AS \"Field\", data_type AS \"Type\", is_nullable AS \"Null\" FROM information_schema.columns WHERE table_name = 'movie_likes' ORDER BY ordinal_position");
    foreach ($columns as $col) {
        echo "- {$col->Field} ({$col->Type}) " . ($col->Null === 'NO' ? 'NOT NULL' : 'NULL') . "\n";
    }
    
    // Show count
    $count = DB::table('movie_likes')->count();
    echo "\nTotal records: $count\n";
    
    // Show sample data
    if ($count > 0) {
        echo "\nSample data:\n";
        $samples = DB::table('movie_likes')->limit(5)->get();
        foreach ($samples as $like) {
            echo "- User {$like->user_id} likes Film {$like->film_id}\n";
        }
    }
} else {
    echo "❌ Table 'movie_likes' does NOT exist\n\n";
    echo "Creating table...\n";
    
    DB::statement("
        CREATE TABLE movie_likes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL,
            film_id BIGINT NOT NULL,
            created_at TIMESTAMP NULL,
            updated_at TIMESTAMP NULL,
            CONSTRAINT uq_movie_likes_user_film UNIQUE (user_id, film_id),
            CONSTRAINT fk_movie_likes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            CONSTRAINT fk_movie_likes_film FOREIGN KEY (film_id) REFERENCES movies(id) ON DELETE CASCADE
        )
    ");
    
    echo "✅ Table created successfully\n";
}

echo "\n========================================\n";
echo "DONE\n";
echo "========================================\n";
