<?php

/**
 * One-off migration: MySQL (XAMPP) -> PostgreSQL.
 * Reads schema+data from live MySQL 'apimoview' and rebuilds it in PostgreSQL 'apimoview'.
 * Idempotent-safe: drops target tables first.
 */

set_error_handler(function ($severity, $message, $file, $line) {
    throw new ErrorException($message, 0, $severity, $file, $line);
});

$mysqlDsn = 'mysql:host=127.0.0.1;port=3306;dbname=apimoview;charset=utf8mb4';
$mysql = new PDO($mysqlDsn, 'root', '', [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);

$pgDsn = 'pgsql:host=127.0.0.1;port=5432;dbname=apimoview';
$pg = new PDO($pgDsn, 'postgres', '12345', [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);
$pg->exec("SET client_encoding TO 'UTF8'");

$schema = 'apimoview';
$mysql->exec("USE `$schema`");

function q($s) { return '"' . str_replace('"', '""', $s) . '"'; }

/**
 * Map a MySQL column type string to PostgreSQL type.
 * Returns [pgType, numericLike]
 */
function mapPgType(string $type): array
{
    $t = strtolower(trim($type));
    if (str_starts_with($t, 'enum'))               return ['text', false];
    if (str_starts_with($t, 'tinyint'))            return ['smallint', true];
    if (str_starts_with($t, 'smallint'))           return ['smallint', true];
    if (str_starts_with($t, 'mediumint'))          return ['integer', true];
    if (str_starts_with($t, 'int'))                return ['integer', true];
    if (str_starts_with($t, 'bigint'))             return ['bigint', true];
    if (str_starts_with($t, 'decimal'))            return ['numeric', true];
    if (str_starts_with($t, 'numeric'))            return ['numeric', true];
    if (str_starts_with($t, 'float') || str_starts_with($t, 'double')) return ['double precision', true];
    if (str_starts_with($t, 'date'))               return ['date', true];
    if (str_starts_with($t, 'datetime') || str_starts_with($t, 'timestamp')) return ['timestamp', true];
    if (str_starts_with($t, 'time'))               return ['time', true];
    if (str_starts_with($t, 'char('))              return [$t, false];
    if (str_starts_with($t, 'varchar'))            return [$t, false];
    if (str_starts_with($t, 'tinytext') || str_starts_with($t, 'mediumtext') ||
        str_starts_with($t, 'text') || str_starts_with($t, 'longtext')) return ['text', false];
    if (str_starts_with($t, 'blob') || str_starts_with($t, 'binary') || str_starts_with($t, 'varbinary')) return ['bytea', true];
    if (str_starts_with($t, 'json'))               return ['jsonb', true];
    if (str_starts_with($t, 'year'))               return ['integer', true];
    return ['text', false];
}

/** Build a PostgreSQL DEFAULT clause from a MySQL COLUMN_DEFAULT literal. */
function pgDefault(?string $def): ?string
{
    if ($def === null) return null;
    $d = trim($def);
    if ($d === '' || strtoupper($d) === 'NULL') return null;
    $low = strtolower($d);
    if (str_starts_with($low, 'current_timestamp') || str_starts_with($low, 'now()')) return 'DEFAULT now()';
    if (str_starts_with($low, '0000-00-00')) return null; // invalid in PG, drop
    // MySQL returns numeric defaults as bare numbers; strings as bare text.
    if (is_numeric($d)) return 'DEFAULT ' . $d;
    return 'DEFAULT ' . "'" . str_replace("'", "''", $d) . "'";
}

$tables = $mysql->query("SHOW FULL TABLES IN `$schema` WHERE Table_type = 'BASE TABLE'")->fetchAll(PDO::FETCH_COLUMN);
sort($tables);
echo "Tables: " . implode(', ', $tables) . "\n\n";

// ---- Step 1: CREATE TABLE (PK + UNIQUE inline, no FKs yet) ----
$createList = [];
$identityTables = []; // table => columns with auto_increment
$sequenceNeeded = [];

foreach ($tables as $table) {
    $cols = $mysql->query(
        "SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, CHARACTER_MAXIMUM_LENGTH
         FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = '$schema' AND TABLE_NAME = " . $mysql->quote($table) . "
         ORDER BY ORDINAL_POSITION"
    )->fetchAll(PDO::FETCH_ASSOC);

    $colDefs = [];
    $numericCols = [];
    $enumCols = [];
    $dateCols = [];

    foreach ($cols as $col) {
        $name = $col['COLUMN_NAME'];
        $isNull = strtoupper($col['IS_NULLABLE']) === 'YES';
        $extra = strtolower($col['EXTRA']);
        $isIdentity = str_contains($extra, 'auto_increment');

        [$pgType, $numericLike] = mapPgType($col['COLUMN_TYPE']);
        $numericCols[$name] = $numericLike;
        $lowType = strtolower($col['COLUMN_TYPE']);
        if (str_starts_with($lowType, 'enum')) $enumCols[$name] = $lowType;
        if (str_starts_with($lowType, 'date') || str_starts_with($lowType, 'datetime') || str_starts_with($lowType, 'timestamp')) $dateCols[$name] = true;

        $def = q($name) . ' ' . $pgType;
        if ($isIdentity) {
            $identityTables[$table][] = $name;
            $def .= ' GENERATED BY DEFAULT AS IDENTITY';
            $hasDefault = false;
        } else {
            $defaultClause = pgDefault($col['COLUMN_DEFAULT']);
            $hasDefault = $defaultClause !== null;
        }

        if (!$isNull) $def .= ' NOT NULL';
        if (!$isIdentity && $hasDefault) $def .= ' ' . $defaultClause;
        $colDefs[] = $def;
    }

    // Primary key
    $pk = $mysql->query(
        "SELECT COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE
         WHERE TABLE_SCHEMA = '$schema' AND TABLE_NAME = " . $mysql->quote($table) . "
           AND CONSTRAINT_NAME = 'PRIMARY'
         ORDER BY ORDINAL_POSITION"
    )->fetchAll(PDO::FETCH_COLUMN);

    // Unique keys (excluding primary)
    $uniqGroups = [];
    $keys = $mysql->query(
        "SELECT s.INDEX_NAME, s.COLUMN_NAME, s.SEQ_IN_INDEX, s.NON_UNIQUE
         FROM information_schema.STATISTICS s
         WHERE s.TABLE_SCHEMA = '$schema' AND s.TABLE_NAME = " . $mysql->quote($table) . "
           AND s.INDEX_NAME <> 'PRIMARY' AND s.NON_UNIQUE = 0
         ORDER BY s.INDEX_NAME, s.SEQ_IN_INDEX"
    )->fetchAll(PDO::FETCH_ASSOC);
    foreach ($keys as $k) {
        $uniqGroups[$k['INDEX_NAME']][$k['SEQ_IN_INDEX']] = $k['COLUMN_NAME'];
    }
    ksort($uniqGroups);

    $pkDef = $pk ? 'PRIMARY KEY (' . implode(', ', array_map('q', $pk)) . ')' : null;
    $uniqDefs = [];
    foreach ($uniqGroups as $iName => $cols) {
        ksort($cols);
        $uniqDefs[] = 'CONSTRAINT ' . q('uq_' . $table . '_' . $iName) . ' UNIQUE (' . implode(', ', array_map('q', $cols)) . ')';
    }

    $allConstraits = array_values(array_filter([$pkDef]));
    foreach ($uniqDefs as $u) $allConstraits[] = $u;

    $createList[$table] = [
        'colDefs'      => $colDefs,
        'constraints'  => $allConstraits,
        'numericCols'  => $numericCols,
        'enumCols'     => $enumCols,
        'dateCols'     => $dateCols,
    ];

    $sql = "CREATE TABLE " . q($table) . " (\n    " . implode(",\n    ", array_merge($colDefs, $allConstraits)) . "\n)";
    $pg->exec('DROP TABLE IF EXISTS ' . q($table) . ' CASCADE');
    $pg->exec($sql);
    echo "  created: $table\n";
}

// ---- Step 2: copy data ----
$rowErrors = 0;
foreach ($tables as $table) {
    $meta = $createList[$table];
    $colNames = $mysql->query(
        "SELECT COLUMN_NAME FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = '$schema' AND TABLE_NAME = " . $mysql->quote($table) . "
         ORDER BY ORDINAL_POSITION"
    )->fetchAll(PDO::FETCH_COLUMN);
    if (!$colNames) continue;

    $quotedCols = array_map('q', $colNames);
    $placeholders = implode(', ', array_fill(0, count($colNames), '?'));
    $insertSql = "INSERT INTO " . q($table) . " (" . implode(', ', $quotedCols) . ") VALUES ($placeholders)";
    $pgInsert = $pg->prepare($insertSql);

    $limit = 1000;
    $offset = 0;
    $total = 0;
    while (true) {
        $rows = $mysql->query("SELECT * FROM `$table` LIMIT $limit OFFSET $offset")->fetchAll(PDO::FETCH_ASSOC);
        if (!$rows) break;
        $pg->beginTransaction();
        foreach ($rows as $row) {
            $vals = [];
            foreach ($colNames as $c) {
                $v = $row[$c];
                if ($v === null) { $vals[] = null; continue; }
                if (isset($meta['dateCols'][$c]) && preg_match('/^0000-00-00/', (string)$v)) {
                    $vals[] = null; continue;
                }
                if (isset($meta['numericCols'][$c]) && is_numeric($v)) {
                    $vals[] = (int)$v; continue;
                }
                // jsonb / text
                $vals[] = (string)$v;
            }
            $pgInsert->execute($vals);
            $total++;
        }
        $pg->commit();
        $offset += $limit;
    }
    echo "  copied: $table ($total rows)\n";
}

// ---- Step 3: foreign keys ----
$fks = $mysql->query(
    "SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME, ORDINAL_POSITION
     FROM information_schema.KEY_COLUMN_USAGE
     WHERE TABLE_SCHEMA = '$schema' AND REFERENCED_TABLE_NAME IS NOT NULL
     ORDER BY TABLE_NAME, CONSTRAINT_NAME, ORDINAL_POSITION"
)->fetchAll(PDO::FETCH_ASSOC);

$deleteRules = [];
$dr = $mysql->query(
    "SELECT CONSTRAINT_NAME, DELETE_RULE FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = '$schema'"
)->fetchAll(PDO::FETCH_KEY_PAIR);
foreach ($dr as $cn => $rule) $deleteRules[$cn] = $rule;

$fkGroups = [];
foreach ($fks as $f) {
    $fkGroups[$f['TABLE_NAME'] . '|' . $f['CONSTRAINT_NAME']][] = $f;
}

foreach ($fkGroups as $group => $parts) {
    [$table, $constraint] = explode('|', $group);
    $cols = [];
    $refCols = [];
    foreach ($parts as $p) {
        $cols[] = q($p['COLUMN_NAME']);
        $refCols[] = q($p['REFERENCED_COLUMN_NAME']);
    }
    $refTable = $parts[0]['REFERENCED_TABLE_NAME'];
    $rule = $deleteRules[$constraint] ?? 'NO ACTION';
    if (strtoupper($rule) === 'RESTRICT') $rule = 'NO ACTION';
    $sql = "ALTER TABLE " . q($table) . " ADD CONSTRAINT " . q('fk_' . $table . '_' . $constraint) .
           " FOREIGN KEY (" . implode(', ', $cols) . ") REFERENCES " . q($refTable) . " (" . implode(', ', $refCols) . ") ON DELETE $rule";
    $pg->exec($sql);
    echo "  fk: $table -> $refTable ($rule)\n";
}

// ---- Step 4: set identity sequences ----
foreach ($identityTables as $table => $cols) {
    foreach ($cols as $col) {
        try {
            $pg->exec(
                "SELECT setval(pg_get_serial_sequence(" . $pg->quote(q($table)) . ", " . $pg->quote($col) . "), COALESCE(MAX(" . q($col) . "), 1), (SELECT COUNT(*) FROM " . q($table) . " WHERE " . q($col) . " IS NOT NULL) > 0) FROM " . q($table)
            );
            echo "  sequence set: $table.$col\n";
        } catch (Throwable $e) {
            echo "  WARN sequence $table.$col: " . $e->getMessage() . "\n";
        }
    }
}

// ---- Step 5: migrations table - ensure every migration file is marked as Ran ----
$known = $mysql->query('SELECT migration, batch FROM migrations')->fetchAll(PDO::FETCH_ASSOC);
$knownNames = array_map(fn($r) => $r['migration'], $known);
$files = glob(__DIR__ . '/database/migrations/*.php');
sort($files);

$maxBatch = 0;
foreach ($known as $r) $maxBatch = max($maxBatch, (int)$r['batch']);

foreach ($files as $f) {
    $name = basename($f, '.php');
    if ($name === '0001_01_01_000001_create_cache_table' || $name === '0001_01_01_000002_create_jobs_table') {
        // these came via raw schema already; only insert if not present below
    }
    if (!in_array($name, $knownNames, true)) {
        $knownNames[] = $name;
        $known[] = ['migration' => $name, 'batch' => $maxBatch + 1];
    }
}

$pg->exec('DELETE FROM "migrations"');
$stmt = $pg->prepare('INSERT INTO "migrations" ("migration", "batch") VALUES (?, ?)');
foreach ($known as $r) {
    $stmt->execute([$r['migration'], (int)$r['batch']]);
}
echo "\n  migrations recorded: " . count($known) . " rows\n";

echo "\nDONE\n";