import dotenv from 'dotenv'
import path from 'path'
import { fileURLToPath } from 'url'
import { query } from '../src/db/pool.js'
import { getTextEmbedding } from '../src/modules/externalImages/clip.service.js'

dotenv.config({ path: path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../.env') })

const backfillTextEmbeddings = async () => {
  const { rows: posts } = await query(
    `select id, title, caption, metadata
     from posts
     where text_embedding is null
       and status = 'published'
     order by published_at desc`
  )
  console.log(`Backfilling text embeddings for ${posts.length} posts...`)
  let count = 0
  for (const post of posts) {
    const tags = post.metadata?.tags || []
    const autoGen = post.metadata?.autoGeneratedTags || []
    const parts = [post.title, post.caption, ...tags, ...autoGen, post.metadata?.matchedEntity?.title].filter(Boolean)
    const words = [...new Set(parts.flatMap(p => p.split(/\s+/).map(w => w.toLowerCase())))]
    const text = words.join(' ').trim()
    if (text.length <= 3) continue
    const textEmb = await getTextEmbedding(text).catch(() => null)
    if (!textEmb) continue
    await query(
      `update posts
       set text_embedding = $2::jsonb,
           updated_at = now()
       where id = $1`,
      [post.id, JSON.stringify(textEmb)],
    )
    count++
    if (count % 10 === 0) console.log(`  Progress: ${count}/${posts.length}`)
  }
  console.log(`Backfilled text embeddings for ${count} posts`)
}

const main = async () => {
  console.log('Starting text embedding backfill...')
  await backfillTextEmbeddings()
  console.log('Backfill complete')
  process.exit(0)
}

main().catch((err) => {
  console.error('Backfill failed:', err)
  process.exit(1)
})
