import dotenv from 'dotenv'
import path from 'path'
import { fileURLToPath } from 'url'
import { query } from '../src/db/pool.js'
import { getImageEmbedding } from '../src/modules/externalImages/clip.service.js'
import { computeZeroShotTags } from '../src/shared/clipZeroShot.service.js'
import { matchKnownEntity, clearEntityCache } from '../src/shared/entityMatch.service.js'

dotenv.config({ path: path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../.env') })

const updatePost = async (id, embedding, autoGeneratedTags, matchedEntity) => {
  const tagsJson = JSON.stringify(autoGeneratedTags)
  const entityJson = matchedEntity ? JSON.stringify(matchedEntity) : 'null'
  await query(
    `update posts
     set embedding = $2::jsonb,
         metadata = jsonb_set(
           jsonb_set(
             coalesce(metadata, '{}'::jsonb),
             '{autoGeneratedTags}', $3::jsonb
           ),
           '{matchedEntity}', $4::jsonb
         ),
         updated_at = now()
     where id = $1`,
    [id, JSON.stringify(embedding), tagsJson, entityJson],
  )
}

const backfillPostsWithoutEmbedding = async () => {
  const { rows: posts } = await query(
    `select p.id, m.public_url
     from posts p
     join post_media pm on pm.post_id = p.id
     join media_assets m on m.id = pm.media_id and m.deleted_at is null
     where p.embedding is null
       and m.public_url is not null
       and p.status = 'published'`
  )
  const grouped = {}
  for (const row of posts) {
    if (!grouped[row.id]) grouped[row.id] = []
    grouped[row.id].push(row.public_url)
  }
  const ids = Object.keys(grouped)
  console.log(`Backfilling ${ids.length} posts without embedding...`)
  let count = 0
  for (const id of ids) {
    const urls = [...new Set(grouped[id])]
    const results = await Promise.allSettled(urls.map((url) => getImageEmbedding(url)))
    const embeddings = results
      .filter((r) => r.status === 'fulfilled' && r.value)
      .map((r) => r.value)
    if (!embeddings.length) continue
    const combined = averageEmbeddings(embeddings)
    if (!combined) continue
    const [autoGeneratedTags, matchedEntity] = await Promise.all([
      computeZeroShotTags(combined),
      matchKnownEntity(combined),
    ])
    await updatePost(id, combined, autoGeneratedTags, matchedEntity)
    count++
  }
  console.log(`Backfilled ${count} posts without embedding`)
}

const averageEmbeddings = (embeddings) => {
  if (!embeddings?.length) return null
  if (embeddings.length === 1) return embeddings[0]
  const dim = embeddings[0].length
  const sum = new Array(dim).fill(0)
  for (const emb of embeddings)
    for (let i = 0; i < dim; i++) sum[i] += emb[i]
  const avg = sum.map((v) => v / embeddings.length)
  let norm = 0
  for (let i = 0; i < avg.length; i++) norm += avg[i] * avg[i]
  norm = Math.sqrt(norm)
  if (norm === 0) return avg
  return avg.map((v) => v / norm)
}

const backfillPostsWithExistingEmbedding = async () => {
  const { rows: posts } = await query(
    `select p.id, p.embedding
     from posts p
     where p.embedding is not null
       and p.status = 'published'
       and (p.metadata->>'autoGeneratedTags' is null or p.metadata->>'autoGeneratedTags' = '[]')
     order by p.published_at desc`
  )
  console.log(`Backfilling ${posts.length} posts with existing embedding...`)
  let count = 0
  for (const post of posts) {
    const [autoGeneratedTags, matchedEntity] = await Promise.all([
      computeZeroShotTags(post.embedding),
      matchKnownEntity(post.embedding),
    ])
    await updatePost(post.id, post.embedding, autoGeneratedTags, matchedEntity)
    count++
  }
  console.log(`Backfilled ${count} posts with existing embedding`)
}

const backfillExternalImages = async () => {
  const { rows: images } = await query(
    `select id, embedding
     from external_images
     where embedding is not null
       and (metadata->>'autoGeneratedTags' is null or metadata->>'autoGeneratedTags' = '[]')`
  )
  console.log(`Backfilling ${images.length} external images...`)
  let count = 0
  for (const img of images) {
    const tags = await computeZeroShotTags(img.embedding)
    if (tags.length) {
      await query(
        `update external_images
         set metadata = jsonb_set(coalesce(metadata, '{}'::jsonb), '{autoGeneratedTags}', $2::jsonb),
             updated_at = now()
         where id = $1`,
        [img.id, JSON.stringify(tags)],
      )
    }
    count++
  }
  console.log(`Backfilled ${count} external images`)
}

const main = async () => {
  console.log('Starting backfill...')
  await backfillPostsWithoutEmbedding()
  await backfillPostsWithExistingEmbedding()
  await backfillExternalImages()
  clearEntityCache()
  console.log('Backfill complete')
  process.exit(0)
}

main().catch((err) => {
  console.error('Backfill failed:', err)
  process.exit(1)
})
